---
apiVersion: v1
kind: Service
metadata:
  name: http-svc
  labels:
    app: sampleapp
    name: http-svc
    env: demo
spec:
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    name: app-pod

---
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  labels:
    app: sampleapp
    name: redis-svc
    env: demo
spec:
  ports:
  - port: 6379
    name: redis
    targetPort: 6379
  selector:
    app: redis-pod
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: sampleapp
    name: sampleapp-deployment
    env: demo
  name: sampleapp-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
        - name: web
          image: abhishekk/sampleapp
          ports: 
            - containerPort: 5000
              name: http
              protocol: TCP
        - name: redis-pod
          image: redis:latest
          ports:
            - containerPort: 6379
              protocol: TCP