---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: demo
spec:
  ports:
  - port: 6379
    name: redis
    targetPort: 6379
  selector:
    name: redis
    app: demo
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  type: LoadBalancer
  ports:
   - port: 5000
     targetPort: 5000
     protocol: TCP
  selector:
    name: web
---
apiVersion: "v1"
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
    app: demo
spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379
          protocol: TCP
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
        - name: web
          image: abhishekk/sampleapp
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP