---
apiVersion: "v1"
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  containers:
    - name: web
      image: abhishekk/sampleapp
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP
---
apiVersion: "v1"
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
    app: demo
spec:
  containers:
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379
          protocol: TCP