---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  selector:
    name: web
  type: NodePort
  ports:
   - port: 80
     targetPort: 5000
     protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: demo
spec:
  ports:
  - port: 6379
    name: redis
    targetPort: 6379
  selector:
    name: redis
    app: demo