---
# flask app deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: sampleapp
    name: web
spec:
  replicas: 2
  revisionHistoryLimit: 100
  template:
    metadata:
      labels:
        app: sampleapp
        name: web
    spec:
      containers:
        - name: web-image
          image: abhishekk/sampleapp
          ports:
            - containerPort: 5000
              name: app-web-port
              protocol: TCP

# app service
---
apiVersion: v1
kind: Service
metadata:
  name: web-deployment
  labels:
    app: sampleapp
    name: web
spec:
  type: NodePort
  ports:
  - port: 32001
    nodePort: 32001
    targetPort: app-web-port
    protocol: TCP
  selector:
    name: web
    app: sampleapp